[package]
name = "signed"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "signed"
path = "src/main.rs"

[dependencies]
assets = { path = "../crates/assets" }
paths = { path = "../crates/paths" }
signed_state = { path = "../crates/signed_state" }
workspace = { path = "../crates/workspace" }

gpui.workspace = true
gpui_platform.workspace = true
gpui_linux.workspace = true
gpui_windows.workspace = true
gpui_macos.workspace = true
dock = { workspace = true }
gpui-component.workspace = true
reqwest_client.workspace = true
log.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
